spring.profiles.active: local

server:
    port:8080
    address:localhost

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xionggao?useUnicode=true&characterEncoding=UTF8
    username: root
    password:

mybatis:
    typeAliasesPackage:   com.xg.java.springboot.user.api.bean
    mapperLocations: classpath*:mapper/*.xml

